name: Update README.md

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - run: npm install
      - run: npm run update-readme
      
      - run: |
          git config user.name.Fili Santillán
          git config user.email fili06604@gmail.com
          git add README.md
          git commit -m "[bot] Update README with latest info"
          git push
    
